PMS/Controllers/ProposalController.cs
using Newtonsoft.Json;
using PMS.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace PMS.Controllers
{
    public class ProposalController : Controller
    {
        private readonly string baseUrl = WebConfigurationManager.AppSettings["ApiUrl"].ToString();

        // GET: ProposeTopic
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Registration()
        {
            ViewBag.Title = "ยื่นเสนอหัวข้อโครงการ";
            return View();
        }

        public ActionResult Upload(int id)
        {
            ProjectModel data = new ProjectModel();

            data.Id = id;
            data.Code = "P64000001";
            data.NameTh = "โครงการทดสอบหมายเลขที่ 1";

            data.StatusId = 1;

            data.CreatedDate = DateTime.Now;

            ViewBag.Title = "อัพโหลดเอกสารโครงการ";

            return View(data);
        }

        public ActionResult Result(int id)
        {
            ProjectModel data = new ProjectModel();

            data.Id = id;
            data.Code = "P64000001";
            data.NameTh = "โครงการทดสอบหมายเลขที่ 1";

            data.StatusId = 1;

            data.CreatedDate = DateTime.Now;

            ViewBag.Title = "ผลการลงทะเบียน";

            return View(data);
        }


        #region Function
        private async Task<List<ProjectModel>> GetAllProposal()
        {
            var result = new ApiResponse<List<ProjectModel>>();
            List<ProjectModel> _list = new List<ProjectModel>();

            using (var client = new HttpClient())
            {
                // Passing service base url  
                client.BaseAddress = new Uri(baseUrl);

                client.DefaultRequestHeaders.Clear();
                // Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage res = await client.GetAsync("api/project/getall");

                // Checking the response is successful or not which is sent using HttpClient  
                if (res.IsSuccessStatusCode)
                {
                    // Storing the response details recieved from web api   
                    var response = res.Content.ReadAsStringAsync().Result;

                    // Deserializing the response recieved from web api and storing into the Employee list  
                    result = JsonConvert.DeserializeObject<ApiResponse<List<ProjectModel>>>(response);
                }
            }

            return result.Data;
        }

        [HttpPost]
        public async Task<ActionResult> Save(ProposalModel data)
        {
            string message = "";

            try
            {
                if (data != null)
                {
                    message = "successful";
                }
                else
                {
                    message = "Upload file error : Can not save, please check your project id and your file.";
                }
            }
            catch (Exception ex)
            {
                message = "Upload file error : " + ex.Message;
            }

            // TODO Save proposal record

            await Task.Delay(1000);

            return Json(new { Data = 1999, Message = message }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> Upload(FileUploadModel data)
        {
            string message = "";

            try
            {
                if (data != null)
                {
                    byte[] fileInBytes = ConvertToByte(data.Files);

                    data.FileType = data.Files.ContentType;
                    data.FileName = data.Files.FileName;
                    data.FileLength = data.Files.ContentLength;

                    if (fileInBytes != null)
                    {
                        var fileBase64String = Convert.ToBase64String(fileInBytes);

                        // TODO Save file record

                        await Task.Delay(1000);

                        message = "successful";
                    }
                }
                else
                {
                    message = "Upload file error : Can not save, please check your project id and your file.";
                }
            }
            catch (Exception ex)
            {
                message = "Upload file error : " + ex.Message;
            }

            return Json(new { Data = 1999, Message = message }, JsonRequestBehavior.AllowGet);
        }

        private byte[] ConvertToByte(HttpPostedFileBase data)
        {
            if (data != null)
            {
                byte[] fileInBytes = new byte[data.ContentLength];
                BinaryReader rdr = new BinaryReader(data.InputStream);
                fileInBytes = rdr.ReadBytes(data.ContentLength);

                rdr.Close();

                return fileInBytes;
            }

            return null;
        }
        #endregion


    }
}

PMS/Views/Proposal/Registration.cshtml
@model PMS.Models.ProposalModel

@{
    List<SelectListItem> members = new List<SelectListItem>();
    List<SelectListItem> teachers = new List<SelectListItem>();

    var studentData = new[]{
                 new SelectListItem{ Value="1",Text="ปลาหยุด"},
                 new SelectListItem{ Value="2",Text="ปลาหวิด"},
                 new SelectListItem{ Value="3",Text="ปลาลีนา"},
                 new SelectListItem{ Value="4",Text="ปลาสลิด"},
                 new SelectListItem{ Value="5",Text="ปลาเผา"},
                 new SelectListItem{ Value="6",Text="ปลาปปิ้ง"},
                 new SelectListItem{ Value="7",Text="ปลากรอบ"},
             };

    var teacherData = new[]{
                 new SelectListItem{ Value="11",Text="จันทร์"},
                 new SelectListItem{ Value="22",Text="โอ"},
                 new SelectListItem{ Value="33",Text="ชา"},
                 new SelectListItem{ Value="44",Text="ปลา"},
                 new SelectListItem{ Value="55",Text="หยุด"}
             };

    members = studentData.ToList();
    teachers = teacherData.ToList();
}

<form id="proposal">
    <div class="wrapper wrapper-content animated fadeInRight form-horizontal">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="row m-md">
                            <div class="col-lg-12">
                                <h2 class="text-center"><i class="fa fa-edit"></i> รายละเอียด</h2>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group">
                                <label class="col-lg-2 control-label">ชื่อหัวข้อ :</label>
                                <div class="col-lg-8">
                                    @Html.TextBoxFor(m => m.Subject, new { @class = "form-control input-sm", @required = "required" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">สมาชิก :</label>
                                <div class="col-lg-8">
                                    @Html.ListBoxFor(m => m.Members, new SelectList(members, "Value", "Text"), new { @class = "select2-ddl form-control", @multiple = "multiple", @required = "required" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">อาจารย์ที่ปรึกษา :</label>
                                <div class="col-lg-8">
                                    @Html.ListBoxFor(m => m.Teachers, new SelectList(teachers, "Value", "Text"), new { @class = "select2-ddl form-control", @multiple = "multiple", @required = "required" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">วัตถุประสงค์ :</label>
                                <div class="col-lg-8">
                                    @Html.TextAreaFor(m => m.Propose, new { @class = "form-control input-sm", @rows = 10, @required = "required" })
                                </div>
                            </div>
                        </div>

                        <div class="row m-md">
                            <div class="col text-center">
                                <button id="btnRegis" type="button" class="btn btn-primary" onclick="btnSumbit()"><i class="fa fa-pencil"></i> ลงทะเบียน</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Styles {
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
}


@section Scripts {
    @Scripts.Render("~/plugins/select2")
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/plugins/validate")

    <script type="text/javascript">
        var form = $("#proposal");
        $(document).ready(function () {
            $(".select2-ddl").select2();
        });



        function btnSumbit() {
            swal({
                title: "",
                text: 'กรุณาตรวจสอบข้อมูลให้ถูกต้องก่อนคลิก (ยืนยัน)',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#1C84C6",
                confirmButtonText: "ยืนยัน",
                cancelButtonText: "ยกเลิก",
                closeOnConfirm: true
            },
                function (isConfirm) {

                    console.log(isConfirm);

                    if (isConfirm) {
                        saveProposal();
                    }
                });
        }

        function saveProposal() {
            $('#loading').show();
            $.ajax({
                type: "POST",
                url: "@Url.Action("Save", "Proposal")",
                data: $("#proposal").serialize(),
                success: function (result) {
                    if (result.Message == "successful") {
                        $('#loading').hide();

                        // Redirect to Next Step
                        window.location.href = '@Url.Action("Upload", "Proposal")/' + result.Data;
                    }

                },
                 error: function (result) {
                    alert('error');
                    console.log(result);
                }
            });
        }

    </script>
}

PMS/Views/Proposal/Result.cshtml
@model PMS.Models.ProjectModel

<div class="wrapper wrapper-content animated fadeInRight form-horizontal">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="row m-md">
                        <div class="col text-center">
                            <i class="fa fa-check-circle text-info fa-5x"></i>
                            <br />
                            <h2 class="text-info">การลงทะเบียนเสร็จสิ้น</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="well m-lg">
                            <div class="row m-md">
                                <div class="col-lg-3">

                                </div>
                                <div class="col-lg-6">
                                    <label class="col-lg-6 text-right">สถานะโครงการ :</label>
                                    <div class="col-lg-6">

                                        @switch (Model.StatusId)
                                        {
                                            case 1:
                                                <label class="badge badge-warning">รอการอนุมัติ</label>
                                                break;
                                            case 2:
                                                <label class="badge badge-primary">ผ่านการอนุมัติ</label>
                                                break;
                                            case 3:
                                                <label class="badge badge-danger">ไม่ผ่านการอนุมัติ</label>
                                                break;
                                            default:
                                                break;
                                        }

                                    </div>
                                </div>
                                <div class="col-lg-3">

                                </div>
                            </div>
                            <div class="row m-md">
                                <div class="col-lg-3">

                                </div>
                                <div class="col-lg-6">
                                    <label class="col-lg-6 text-right">รหัสโครงการ :</label>
                                    <div class="col-lg-6">
                                        <label class="label label-default">@Model.Code</label>
                                    </div>
                                </div>
                                <div class="col-lg-3">

                                </div>
                            </div>
                            <div class="row m-md">
                                <div class="col-lg-3">

                                </div>
                                <div class="col-lg-6">
                                    <label class="col-lg-6 text-right">ชื่อโครงการ :</label>
                                    <div class="col-lg-6">
                                        <label class="label label-default">@Model.NameTh</label>
                                    </div>
                                </div>
                                <div class="col-lg-3">

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row m-md">
                        <div class="col-lg-3">

                        </div>
                        <div class="col-lg-6">
                            <div class="col-lg-12 text-center">
                                <button class="btn btn-md btn-success" type="button" onclick="finish()"><i class="fa fa-check"></i> ตกลง</button>
                            </div>
                        </div>
                        <div class="col-lg-3">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

        $(document).ready(function () {

        });

        function finish() {
            $('#loading').show();

            // Redirect to Next Step
            window.location.href = '@Url.Action("Report", "Project")';
        }

</script>

PMS/Views/Proposal/Upload.cshtml
@model PMS.Models.ProjectModel

<form id="proposalFile">
    @Html.HiddenFor(m => m.Id)

    <div class="wrapper wrapper-content animated fadeInRight form-horizontal">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="row m-md">
                            <div class="col-lg-12">
                                <h2 class="text-center"><i class="fa fa-cloud-upload"></i> อัพโหลดเอกสาร</h2>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group">
                                <label class="col-lg-2 text-right">รหัสโครงการ:</label>
                                <div class="col-lg-1 text-left">
                                    <label class="label label-default">@Model.Code</label>
                                </div>

                                <label class="col-lg-2 text-right">ชื่อโครงการ:</label>
                                <div class="col-lg-7 text-left">
                                    <label class="label label-default">@Model.NameTh</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 text-right">ไฟล์เอกสาร :</label>
                                <div class="col-lg-8">
                                    <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                        <div class="form-control" data-trigger="fileinput"><i class="glyphicon glyphicon-file fileinput-exists"></i><span class="fileinput-filename"></span></div>
                                        <span class="input-group-addon btn btn-default btn-file"><span class="fileinput-new">เลือกไฟล์</span><span class="fileinput-exists">เปลี่ยน</span><input id="file-upload" type="file" name="fileUpload" required></span>
                                        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">ลบ</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row m-md">
                            <div class="col text-center">
                                <button type="button" class="btn btn-primary" onclick="btnSumbit()"><i class="fa fa-cloud-upload"></i> อัพโหลด</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section Styles {
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/jasnyBootstrap")

    <script type="text/javascript">

        $(document).ready(function () {

        });

        function btnSumbit() {
            var fileUpload = $("#file-upload").get(0);
            var files = fileUpload.files;

            if (files.length > 0) {
                swal({
                    title: "",
                    text: 'กรุณาตรวจสอบข้อมูลให้ถูกต้องก่อนคลิก (ยืนยัน)',
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#1C84C6",
                    confirmButtonText: "ยืนยัน",
                    cancelButtonText: "ยกเลิก",
                    closeOnConfirm: true
                },
                    function (isConfirm) {

                        console.log(isConfirm);

                        if (isConfirm) {
                            saveFile();
                        }
                    });
            }
        }

        function saveFile() {
            $('#loading').show();

            var fileUpload = $("#file-upload").get(0);
            var files = fileUpload.files;
            var data = new FormData();

            if (files.length > 0)
            {
                for (var i = 0; i < files.length; i++) {
                    data.append("Files", files[i]);
                }

                //Add the input element values
                data.append("Id", $("#Id").val());

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Upload", "Proposal")",
                    contentType: false,
                    processData: false,
                    data: data,
                    success: function (result) {

                        if (result.Message == "successful") {
                             $('#loading').hide();

                             // Redirect to Next Step
                             window.location.href = '@Url.Action("Result", "Proposal")?id=' + result.Data;
                        }

                    },
                    error: function () {
                        alert("There was error uploading files!");
                    }
                });
            }
        }

    </script>
}