PMS/Controllers/AssessmentController.cs
using PMS.Helpers;
using PMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace PMS.Controllers
{
    public class AssessmentController : Controller
    {
        ApiHelper api = new ApiHelper();

        // GET: Assessment
        public ActionResult Index()
        {
            ViewBag.Title = "ประเมินโครงการ";
            return View();
        }

        public ActionResult AssessmentProject(int? projectId)
        {
            return View();
        }

        public ActionResult _ListAssessmentProject(int? projectId)
        {
            List<AssessmentProjectModel> list = new List<AssessmentProjectModel>();

            for (int i = 0; i < 9; i++)
            {
                list.Add(new AssessmentProjectModel { Id = i + 1, WeekName = "สัปดาห์ที่ " + (i + 1), WorkDiscription = "ประเมินผลเสร็จสิ้น", Point = 20, CreatedDate = DateTime.Now, Status = 1 });
            }

            for (int i = list.Count; i < 16; i++)
            {
                list.Add(new AssessmentProjectModel { Id = i + 1, WeekName = "สัปดาห์ที่ " + (i + 1), WorkDiscription = "รอการประเมินผล", Point = 0, CreatedDate = DateTime.Now, Status = 2 });
            }

            ViewBag.Title = "การประเมินโครงการ";
            ViewBag.Project = "ทดสอบหมายเลขที่ 1";

            return PartialView(list);
        }

        public ActionResult _TblAssessmentPartial()
        {
            List<ProjectModel> list = new List<ProjectModel>();

            // trick to prevent deadlocks of calling async method 
            // and waiting for on a sync UI thread.
            var syncContext = SynchronizationContext.Current;
            SynchronizationContext.SetSynchronizationContext(null);

            //  this is the async call, wait for the result (!)
            list = api.GetAllProject().Result;

            // restore the context
            SynchronizationContext.SetSynchronizationContext(syncContext);

            return PartialView(list);
        }

        public ActionResult _ModalAssessmentPartial(int? Id)
        {
            AssessmentProjectModel model = new AssessmentProjectModel();

            model.Id = 1;
            model.WeekName = "สัปดาห์ที่ 1";
            model.WorkDiscription = "ประเมินผลเสร็จสิ้น";
            model.Status = 1;
            model.Point = 20;
            model.CreatedDate = DateTime.Now;

            List<QuestionAssessmentModel> list = new List<QuestionAssessmentModel>();

            for (int i = 0; i < 3; i++)
            {
                list.Add(new QuestionAssessmentModel { Id = i + 1, AssessmentId = Id.Value, Question = "หัวข้อประเมินโครงการ " + i, IsAssesment = true, CreatedDate = DateTime.Now });
            }

            for (int i = list.Count; i < 6; i++)
            {
                list.Add(new QuestionAssessmentModel { Id = i + 1, AssessmentId = Id.Value, Question = "หัวข้อประเมินโครงการ " + i, IsAssesment = false, CreatedDate = DateTime.Now });
            }

            model.ListQuestionAsset = list;

            return PartialView(model);
        }
    }
}

PMS/Views/Assessment/AssessmentProject.cshtml
<div class="row">
    <div id="assessment">

    </div>
</div>

<div class="modal inmodal fade" id="assetModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div id="assetModalcontent">

        </div>
    </div>
</div>


@section Styles {
    @Styles.Render("~/plugins/awesomeCheckboxStyles")
}

@section Scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            loadAssessment();
        });

        function loadAssessment() {
            $.ajax({
                url: '@Url.Action("_ListAssessmentProject", "Assessment")',
                //type: "GET",
                data: { projectId: 1 },
                success: function (response) {
                    $('#assessment').html(response);
                },
                error: function (response) {
                    $('#assessment').html(response);
                }
            });
        }

        function modalAssessment(id) {
            $.ajax({
                url: '@Url.Action("_ModalAssessmentPartial", "Assessment")',
                data: { Id: id },
                success: function (response) {
                    $('#assetModal').modal('show');
                    $('#assetModalcontent').html(response);
                },
                error: function (response) {
                    $('#assetModal').modal('show');
                    $('#assetModal').html(response);
                }
            });
        }

        function saveAssesment() {
            $.ajax({
                url: '@Url.Action("", "Assessment")',
                data: { Id: id },
                success: function (response) {
                    $('#assetModal').modal('show');
                    $('#assetModalcontent').html(response);
                },
                error: function (response) {
                    $('#assetModal').modal('show');
                    $('#assetModal').html(response);
                }
            });
        }

    </script>
}

PMS/Views/Assessment/Index.cshtml
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h2><i class="fa fa-tasks"></i> รายการ</h2>
                </div>
                <div class="ibox-content">
                    @Html.Action("_TblAssessmentPartial", "Assessment")
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataTables")

    <script type="text/javascript">
        $(document).ready(function () {

        });

    </script>
}

PMS/Views/Assessment/_ListAssessmentProject.cshtml
@model IEnumerable<PMS.Models.AssessmentProjectModel>

@{ 
    double averagePercent = 100 / Model.Count();
    double sumPoint = Model.Sum(s => s.Point);
    double sumPointPercent = Model.Where(w => w.Status == 1).Count() * averagePercent;
}

<div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="ibox-content m-b-sm border-bottom">
            <div class="p-xs">
                <div class="pull-left m-r-md">

                </div>
                <h2>@ViewBag.Project</h2>
                <span>การประเมินผลของคณะที่ปรึกษา</span>
            </div>
        </div>

        <div class="ibox-content forum-container">

            <div class="forum-title">
                <div class="pull-right forum-desc">
                    <samll>~ <strong>@sumPointPercent.ToString("N2")</strong> %</samll>
                </div>
                <div class="pull-right forum-desc">
                    <samll> รวม: <strong>@sumPoint.ToString("N2")</strong> คะแนน </samll>
                </div>
                <h3>หัวข้อ</h3>
            </div>

            @if (Model.Any())
            {
                foreach (var item in Model)
                {
                    string active = "";
                    string cssClass = "fa-circle-o";

                    if (item.Status == 1)
                    {
                        active = "active";
                        cssClass = "fa-check-circle-o";
                    }

                    <div class="forum-item @active">
                        <div class="row">
                            <div class="col-md-9">
                                <div class="forum-icon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <a href="#" class="forum-item-title" onclick="modalAssessment(@item.Id)">@item.WeekName</a>
                                <div class="forum-sub-title">@item.WorkDiscription</div>
                            </div>
                            <div class="col-md-1 forum-info">
                    
                            </div>
                            <div class="col-md-1 forum-info">
                                <span class="views-number">
                                    <i class="fa @cssClass"></i>
                                </span>
                            </div>
                            <div class="col-md-1 forum-info">
                                <span class="views-number">
                                    @item.Point.ToString("N0")
                                </span>
                                <div>
                                    <small>คะแนน</small>
                                </div>
                            </div>
                        </div>
                    </div>                
                }
             }
        </div>
    </div>
</div>

PMS/Views/Assessment/_ModalAssessmentPartial.cshtml
@model PMS.Models.AssessmentProjectModel

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">@Model.WeekName</h4>
        <small class="font-bold">@Model.WorkDiscription</small>
    </div>
    <div class="modal-body">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>ลำดับ</th>
                    <th>รายการ</th>
                    <th class="text-center">ผลการประเมิน</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ListQuestionAsset.Any())
                {
                    int row = 1;
                    foreach (var item in Model.ListQuestionAsset)
                    {
                        <tr>
                            <td>@row</td>
                            <td>@item.Question</td>
                            <td class="text-center ">
                                @if (item.IsAssesment)
                                {
                                    <div class="checkbox checkbox-primary" style="margin: 0 auto;">
                                        <input type="checkbox" disabled checked="checked">
                                        <label></label>
                                    </div> 
                                }
                                else
                                {
                                    <div class="checkbox checkbox-primary" style="margin: 0 auto;">
                                        <input type="checkbox">
                                        <label></label>
                                    </div>
                                }
                            </td>
                        </tr>
                        row++;
                    }
                }

            </tbody>

        </table>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-primary">บันทึก</button>
        <button type="button" class="btn btn-white" data-dismiss="modal">ปิด</button>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
    });
</script>

PMS/Views/Assessment/_TblAssessmentPartial.cshtml
@model IEnumerable<PMS.Models.ProjectModel>

<table class="table table-striped table-bordered table-hover dataTables">
    <thead>
        <tr>
            <th class="text-center">
                #
            </th>
            <th>
                ชื่อโครงการ (ภาษาไทย)
            </th>
            <th>
                ชื่อโครงการ (English)
            </th>
            <th>
                วันที่เริ่มโครงการ
            </th>
            <th class="text-center">
                สถานะโครงการ
            </th>
        </tr>
    </thead>
    <tbody>
        @{ int row = 1; }
        @foreach (var item in Model)
        {
            <tr style="cursor: pointer;" onclick="assessment(@item.Id)">
                <td class="text-center">
                    @row
                </td>
                <td>
                    @item.NameTh
                </td>
                <td>
                    @item.NameEn
                </td>
                <td>
                    @item.CreatedDate.Value.ToString("dd/MM/yyyy HH:mm:ss")
                </td>
                <td class="text-center">
                    @*@if (item.PStatusId == 1)
                    {
                        <label class="label">เสนอหัวข้อโครงการ</label>
                    }
                    @if (item.PStatusId == 2)
                    {
                        <label class="label label-warning">กำลังดำเนินการ</label>
                    }
                    @if (item.PStatusId == 3)
                    {
                        <label class="label label-primary">เสร็จสิ้น</label>
                    }*@
                </td>
            </tr>
    
            row++;
    
        }
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function () {
        $('.dataTables').DataTable({
                pageLength: 15,
                lengthMenu: [[15, 30, 45, -1], [15, 30, 45, "ทั้งหมด"]],
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'csv' },
                    { extend: 'excel', title: 'ExampleFile' },
                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]

            });
    });

    function assessment(projectId) {
        window.open('@Url.Action("AssessmentProject", "Assessment")' + '?projectId=' + projectId, '_blank');
    }

</script>